### ISSUE TITLE
fails on units like "ms"

### ISSUE THREAD

**Issue by sappelhoff** [sensein/cmixf#3]
Hey @satra thanks for such a clean package!

1. I installed the dev version as described in the README
1. I ran `cmixf` from the CLI to start the program
1. I entered `1ms` which should be 1 millisecond

Traceback:

```
cmixf > 1ms
type='REAL', value='1'
type='UNITC', value='m'
type='UNITC', value='s'
sly: Syntax error at line 1, token=UNITC
Traceback (most recent call last):
  File "/home/stefanappelhoff/miniconda3/bin/cmixf", line 11, in <module>
    load_entry_point('cmixf', 'console_scripts', 'cmixf')()
  File "/home/stefanappelhoff/Desktop/bids/cmixf/cmixf/parser.py", line 218, in main
    print(parser.parse(lexer.tokenize(text)))
  File "/home/stefanappelhoff/miniconda3/lib/python3.7/site-packages/sly/yacc.py", line 2119, in parse
    tok = self.error(errtoken)
  File "/home/stefanappelhoff/Desktop/bids/cmixf/cmixf/parser.py", line 204, in error
    raise RuntimeError(f"Could not parse {t}")
RuntimeError: Could not parse Token(type='UNITC', value='s', lineno=1, index=2)

```

Similar errors for:
- 1uV
- 1µV
- 1kBq

(and probably more)

**Comment by satra** [comment]
thank you @sappelhoff - time to add some more tests :)

this is the part about regex's interaction with the python library that i am depending on. sending PR to fix these while not breaking others !

**Comment by sappelhoff** [comment]
nice, thanks for the fast fix :+1: 

are you going to make this package more usable for non-devs? E.g., pypi package and some simple usage instructions?

We could add a line about this validator in the BIDS units PR, so that people who are uncertain with their formatting can use this package to check. 

WDYT?

**Comment by satra** [comment]
here you go: https://pypi.org/project/cmixf/0.1.0/ as an initial release. 

we can now automate the process and updates from github, including better instructions.

**Comment by satra** [comment]
automation now in place.
