### ISSUE TITLE
Liters are not validated when combined with prefix

### ISSUE THREAD

**Issue by sappelhoff** [sensein/cmixf#6]
```
# 1 Liter works
cmixf > 1L
type='REAL', value='1'
type='UNITC', value='L'
1L

# 1mL does not work
cmixf > 1mL
type='REAL', value='1'
type='UNITC', value='m'
type='UNITC', value='L'
sly: Syntax error at line 1, token=UNITC
Traceback (most recent call last):
  File "/home/stefanappelhoff/miniconda3/bin/cmixf", line 11, in <module>
    load_entry_point('cmixf', 'console_scripts', 'cmixf')()
  File "/home/stefanappelhoff/Desktop/bids/cmixf/cmixf/parser.py", line 219, in main
    print(parser.parse(lexer.tokenize(text)))
  File "/home/stefanappelhoff/miniconda3/lib/python3.7/site-packages/sly/yacc.py", line 2119, in parse
    tok = self.error(errtoken)
  File "/home/stefanappelhoff/Desktop/bids/cmixf/cmixf/parser.py", line 205, in error
    raise RuntimeError(f"Could not parse {t}")
RuntimeError: Could not parse Token(type='UNITC', value='L', lineno=1, index=2)
```

**Comment by satra** [comment]
it's going to be between liters and moles. i'll fix this. also i will update the test so we actually test for all valid combinations instead of hacking it based on examples :)

**Comment by satra** [comment]
should be a lot more robust now - can't say the tests cover every corner case, but it covers about 800 more combos :)

**Comment by sappelhoff** [comment]
nice, thanks for implementing this so quickly ... it really motivated me to finally push that units PR to be merged

**Comment by satra** [comment]
it was a little weekend hack to demonstrate that the hard part of a parser is actually the formulation of the parsing tokens and rules, which was already done in the CMIXF-12 document. turning it into code is not too complicated. 

also we can update the code to normalization of unicode symbols to whatever is decided. i don't have a strong preference
